---
title: "Untitled"
author: "Victor Nugraha"
date: "7/23/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(rsconnect)

#data cleanup
library(tidyverse)
library(lubridate)

#data visualizaion
library(ggplot2)
library(plotly)
library(glue)

#data collection
library(quantmod)
library(tidyquant)

#data processing
library(TTR)

#cross validation
library(rsample)
library(UBL)
library(imbalance)
library(caret)

#model
library(partykit)
library(stats)
library(e1071)
```



```{r}
hoki_validasi <- tq_get(x = "HOKI.JK", #Nama saham 
                        get = "stock.prices", #"stock.prices" berarti mengambil dari Yahoo Finance
                        from = " 2016-01-01",
                        to = "2017-12-31")

tail(hoki_validasi)
```

```{r}
colSums(is.na(hoki_validasi))
```

```{r}
hoki_sma2 <- hoki_validasi

# SMA 5
hoki_sma2$SMA5 <- SMA(Ad(hoki_sma2),
                n = 5)
  
# SMA 25
hoki_sma2$SMA25 <- SMA(Ad(hoki_sma2),
                n = 25)

# SMA 55
hoki_sma2$SMA55 <- SMA(Ad(hoki_sma2),
                      n = 55)

# SMA 70
hoki_sma2$SMA70 <- SMA(Ad(hoki_sma2),
                n =70)
```


```{r}
hoki_sma2 <- hoki_sma2 %>%
  mutate(
    signal.SMA = case_when(
      close < lag(SMA5, 1) & SMA25 < lag(SMA55, 1) ~ "Buy",
      close > lag(SMA70, 1) & SMA25 > lag(SMA55, 1) ~ "Sell",
      TRUE ~ "Hold"
    ),
    previous_signal.SMA = lag(signal.SMA, 1),
    decision.SMA = case_when(
      signal.SMA == previous_signal.SMA ~ "Hold",
      TRUE ~ signal.SMA
    )
  )
```


```{r}
hoki_sma2 %>% 
  filter(decision.SMA != "Hold" & ! is.na(SMA70))
```

```{r}
hoki_ema2 <- hoki_validasi

# EMA 5
hoki_ema2$EMA5 <- EMA(Ad(hoki_ema2),
                n = 5)

# EMA 30
hoki_ema2$EMA30 <- EMA(Ad(hoki_ema2),
                n = 30)

# EMA 40
hoki_ema2$EMA50 <- EMA(Ad(hoki_ema2),
                n = 50)

# EMA 60
hoki_ema2$EMA60 <- EMA(Ad(hoki_ema2),
                n = 60)
```

```{r}
hoki_ema2 <- hoki_ema2 %>% 
  mutate(
    signal.EMA = case_when(
      close < lag(EMA5, 1) & EMA30 < lag(EMA50, 1) ~ "Buy",
      close > lag(EMA60, 1) & EMA30 > lag(EMA50, 1) ~ "Sell",
      TRUE ~ "Hold"# Otherwise sell
    ),
    previous_signal.EMA = lag(signal.EMA, 1), 
    decision.EMA = case_when( 
      signal.EMA == previous_signal.EMA ~ "Hold",
      TRUE ~ signal.EMA
    )
  )
```


```{r}
hoki_ema2 %>% 
  filter(decision.EMA != "Hold" & ! is.na(EMA60))
```

```{r}
# Membuat objek baru
hoki_macd2 <- hoki_validasi

# EMA 10
hoki_macd2$EMA10 <- EMA(Ad(hoki_macd2),
                n = 10)

# EMA 15
hoki_macd2$EMA15 <- EMA(Ad(hoki_macd2),
                n = 15)

# EMA 50
hoki_macd2$EMA50 <- EMA(Ad(hoki_macd2),
                n = 50)

# MACD
hoki_macd2$MACD <- hoki_macd2$EMA15 - hoki_macd2$EMA50
```


```{r}
hoki_macd2 <- hoki_macd2 %>% 
  mutate(
    signal.MACD = case_when(
      adjusted < lag(hoki_macd2$EMA10, 1) & MACD < 0 & lag(MACD, 1) < MACD ~ "Buy", 
      adjusted > lag(hoki_macd2$EMA10, 1) & MACD > 0 & lag(MACD, 1) > MACD ~ "Sell", 
      TRUE ~ "Hold"
    ),
    previous_signal.MACD = lag(signal.MACD, 1), 
    decision.MACD = case_when( 
      signal.MACD == previous_signal.MACD ~ "Hold",
      TRUE ~ signal.MACD
    )
  )
```


```{r}
hoki_macd2 %>% 
  filter(decision.MACD != "Hold" )
```


```{r}
# Membuat objek baru
hoki_rsi2 <- hoki_validasi

# RSI 10
hoki_rsi2$RSI10 <- RSI(Ad(hoki_rsi2),
                     n =10)

# RSI 14
hoki_rsi2$RSI14 <- RSI(Ad(hoki_rsi2), 
                      n=14)

# RSI 40
hoki_rsi2$RSI40 <- RSI(Ad(hoki_rsi2), 
                      n=40)

# RSI 65
hoki_rsi2$RSI65 <- RSI(Ad(hoki_rsi2), 
                      n=65)
```


```{r}
hoki_rsi2 <- hoki_rsi2 %>% 
  mutate(
    signal.RSI = case_when(
      close < lag(close,1) & RSI10 > RSI14 & RSI10 < RSI65 ~ "Sell",
      close > lag(close,1) & RSI10 < RSI14 & RSI10 > RSI40 ~ "Buy",
      TRUE ~ "Hold"
    ),
    previous_signal.RSI = lag(signal.RSI, 1),
    decision.RSI = case_when( 
      signal.RSI == previous_signal.RSI ~ "Hold",
      TRUE ~ signal.RSI
    )
  )
```


```{r}
hoki_rsi2 %>% 
  filter(decision.RSI != "Hold")
```


```{r}
# Menggabungkan kedalam sebuah data frame baru
hoki_analisa <- cbind(hoki_validasi,hoki_sma2$SMA5, hoki_sma2$SMA25, hoki_sma2$SMA55, hoki_sma2$SMA70, hoki_ema2$EMA5, hoki_ema2$EMA30, hoki_ema2$EMA50, hoki_ema2$EMA60, hoki_macd2$EMA10, hoki_macd2$EMA15, hoki_macd2$MACD, hoki_rsi2$RSI10, hoki_rsi2$RSI14, hoki_rsi2$RSI40, hoki_rsi2$RSI65, hoki_sma2$decision.SMA, hoki_ema2$decision.EMA, hoki_macd2$decision.MACD, hoki_rsi2$decision.RSI)

# Mengubah nama kolom
colnames(hoki_analisa) <- c("symbol", "date", "open", "high", "low", "close", "volume", "adjusted", "SMA5", "SMA25", "SMA55", "SMA70", "EMA5", "EMA30", "EMA50", "EMA60", "EMA10", "EMA15", "MACD", "RSI10", "RSI14", "RSI40", "RSI65", "decision.SMA", "decision.EMA", "decision.MACD", "decision.RSI")

head(hoki_analisa)
```


```{r}
hoki_analisa <- hoki_analisa %>% 
  mutate(
    final_decision = case_when(
      decision.SMA == "Buy" &  decision.EMA == "Buy" & decision.MACD == "Buy" & decision.RSI == "Buy" ~ "Buy",
      decision.SMA == "Sell" &  decision.EMA == "Buy" & decision.MACD == "Buy" & decision.RSI == "Buy" ~ "Buy",
      decision.SMA == "Buy" &  decision.EMA == "Sell" & decision.MACD == "Buy" & decision.RSI == "Buy" ~ "Buy",
      decision.SMA == "Buy" &  decision.EMA == "Buy" & decision.MACD == "Sell" & decision.RSI == "Buy" ~ "Buy",
      decision.SMA == "Buy" &  decision.EMA == "Buy" & decision.MACD == "Buy" & decision.RSI == "Sell" ~ "Buy",
      decision.SMA == "Sell" &  decision.EMA == "Sell" & decision.MACD == "Sell" & decision.RSI == "Sell" ~ "Sell",
      decision.SMA == "Buy" &  decision.EMA == "Sell" & decision.MACD == "Sell" & decision.RSI == "Sell" ~ "Sell",
      decision.SMA == "Sell" &  decision.EMA == "Buy" & decision.MACD == "Sell" & decision.RSI == "Sell" ~ "Sell",
      decision.SMA == "Sell" &  decision.EMA == "Sell" & decision.MACD == "Buy" & decision.RSI == "Sell" ~ "Sell",
      decision.SMA == "Sell" &  decision.EMA == "Sell" & decision.MACD == "Sell" & decision.RSI == "Buy" ~ "Sell",
      TRUE ~ "Hold"
    )
  )

hoki_analisa %>% 
  filter(final_decision != "Hold")
```


```{r}
hoki_analisa2 <- hoki_analisa %>% 
  mutate(
    final_decision = case_when(
      decision.SMA == "Buy" &  decision.EMA == "Buy" & decision.MACD == "Buy" & decision.RSI == "Buy" | decision.MACD == "Buy" | decision.RSI == "Buy" ~ "Buy",
      decision.SMA == "Sell" &  decision.EMA == "Buy" & decision.MACD == "Buy" & decision.RSI == "Buy" | decision.MACD == "Buy" | decision.RSI == "Buy" ~ "Buy",
      decision.SMA == "Buy" &  decision.EMA == "Sell" & decision.MACD == "Buy" & decision.RSI == "Buy" | decision.MACD == "Buy" | decision.RSI == "Buy" ~ "Buy",
      decision.SMA == "Buy" &  decision.EMA == "Buy" & decision.MACD == "Sell" & decision.RSI == "Buy" | decision.MACD == "Buy" | decision.RSI == "Buy" ~ "Buy",
      decision.SMA == "Buy" &  decision.EMA == "Buy" & decision.MACD == "Buy" & decision.RSI == "Sell" | decision.MACD == "Buy" | decision.RSI == "Buy" ~ "Buy",
      decision.SMA == "Sell" &  decision.EMA == "Sell" & decision.MACD == "Sell" & decision.RSI == "Sell" | decision.MACD == "Sell" | decision.RSI == "Sell" ~ "Sell",
      decision.SMA == "Buy" &  decision.EMA == "Sell" & decision.MACD == "Sell" & decision.RSI == "Sell" | decision.MACD == "Sell" | decision.RSI == "Sell" ~ "Sell",
      decision.SMA == "Sell" &  decision.EMA == "Buy" & decision.MACD == "Sell" & decision.RSI == "Sell" | decision.MACD == "Sell" | decision.RSI == "Sell" ~ "Sell",
      decision.SMA == "Sell" &  decision.EMA == "Sell" & decision.MACD == "Buy" & decision.RSI == "Sell" | decision.MACD == "Sell" | decision.RSI == "Sell" ~ "Sell",
      decision.SMA == "Sell" &  decision.EMA == "Sell" & decision.MACD == "Sell" & decision.RSI == "Buy" | decision.MACD == "Sell" | decision.RSI == "Sell" ~ "Sell",
      TRUE ~ "Hold"
    )
  )
```


```{r}
hoki_analisa2 %>%
  select(c("date", "open", "close", "final_decision")) %>% 
  filter(final_decision != "Hold")
```

```{r}
hoki_x <- hoki_analisa2[71:130,]
```


```{r}
hoki_dt <- readRDS("hoki_dt.RDS")
hoki_rf <- readRDS("hoki_forest.RDS")
```

```{r}
dt_pred <- predict(hoki_dt, hoki_x, type = "response")
head(dt_pred)
```

```{r}
eval_dt_validasi <- confusionMatrix(data = dt_pred,
                reference = as.factor(hoki_x$final_decision))

table(hoki_x$final_decision)
eval_dt_validasi
```

```{r}
hoki_x$pred_dt <- dt_pred

hoki_x
```

```{r}
bbri_dt_backtest <- bbri_x %>%
  filter(pred_dt != "Hold") %>%
  select(c("date", "open", "close", "final_decision", "pred_dt")) %>%
  mutate(
    stock_buy = case_when(
      pred_dt == "Buy" ~ "1",
      TRUE ~ "0"
    )
  )

bbri_dt_backtest <- bbri_dt_backtest %>%
  group_by(grp = cumsum(stock_buy==0)) %>%
  mutate(total_stock = ifelse(stock_buy==1, lag(cumsum(stock_buy==1))+1,0)) %>%
  ungroup() %>%
  select(-grp) %>%
  as.data.frame()

bbri_dt_backtest <- bbri_dt_backtest %>%
  mutate(
    stock_sell = ifelse(pred_dt == "Sell", lag(total_stock),0)
    )

bbri_dt_backtest <- bbri_dt_backtest %>%
  mutate(
    price_stock_bought = ifelse(pred_dt == "Buy", open*100,0)
    )

bbri_dt_backtest <- bbri_dt_backtest %>%
  group_by(grp = cumsum(stock_buy==0)) %>%
  mutate(commulative_stock_price = ifelse(stock_buy==1, cumsum(price_stock_bought),0)) %>%
  ungroup() %>%
  select(-grp) %>%
  as.data.frame()

bbri_dt_backtest <- bbri_dt_backtest %>%
  mutate(
    avg_price = ifelse(pred_dt == "Sell", lag(commulative_stock_price)/stock_sell,0)
    )

bbri_dt_backtest <- bbri_dt_backtest %>%
  mutate(
    profit = ifelse(pred_dt == "Sell", (close*100 - avg_price)*stock_sell ,0)
    )

bbri_dt_backtest

bbri_dt_backtest %>%
  filter(profit != 0 & profit != "NaN") %>%
  summarise(total_proft = sum(profit))
```


```{r}
rf_pred <- predict(hoki_rf, hoki_x, type = "raw")
head(rf_pred)
```

```{r}
eval_rf_validasi <- confusionMatrix(data = rf_pred,
                reference = as.factor(hoki_x$final_decision))

table(hoki_x$final_decision)
eval_rf_validasi
```



```{r}
hoki_x$pred_rf <- rf_pred

hoki_x
```

```{r}
bbri_rf_backtest <- bbri_x %>% 
  filter(pred_rf != "Hold") %>% 
  select(c("date", "open", "close", "final_decision", "pred_rf")) %>% 
  mutate(
    stock_buy = case_when(
      pred_rf == "Buy" ~ "1",
      TRUE ~ "0"
    )
  )

bbri_rf_backtest <- bbri_rf_backtest %>% 
  group_by(grp = cumsum(stock_buy==0)) %>%
  mutate(total_stock = ifelse(stock_buy==1, lag(cumsum(stock_buy==1))+1,0)) %>% 
  ungroup() %>% 
  select(-grp) %>%
  as.data.frame()

bbri_rf_backtest <- bbri_rf_backtest %>% 
  mutate(
    stock_sell = ifelse(pred_rf == "Sell", lag(total_stock),0)
    )

bbri_rf_backtest <- bbri_rf_backtest %>% 
  mutate(
    price_stock_bought = ifelse(pred_rf == "Buy", open*100,0)
    )

bbri_rf_backtest <- bbri_rf_backtest %>% 
  group_by(grp = cumsum(stock_buy==0)) %>%
  mutate(commulative_stock_price = ifelse(stock_buy==1, cumsum(price_stock_bought),0)) %>% 
  ungroup() %>% 
  select(-grp) %>%
  as.data.frame()

bbri_rf_backtest <- bbri_rf_backtest %>% 
  mutate(
    avg_price = ifelse(pred_rf == "Sell", lag(commulative_stock_price)/stock_sell,0)
    )

bbri_rf_backtest <- bbri_rf_backtest %>% 
  mutate(
    profit = ifelse(pred_rf == "Sell", (close*100 - avg_price)*stock_sell ,0)
    )

bbri_rf_backtest

bbri_rf_backtest %>% 
  filter(profit != 0 & profit != "NaN") %>% 
  summarise(total_proft = sum(profit))
```