---
title: "Untitled"
author: "Victor Nugraha"
date: "7/23/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(rsconnect)

#data cleanup
library(tidyverse)
library(lubridate)

#data visualizaion
library(ggplot2)
library(plotly)
library(glue)

#data collection
library(quantmod)
library(tidyquant)

#data processing
library(TTR)

#cross validation
library(rsample)
library(UBL)
library(imbalance)
library(caret)

#model
library(partykit)
library(stats)
library(e1071)
```



```{r}
isat_validasi <- tq_get(x = "ISAT.JK", #Nama saham 
                        get = "stock.prices", #"stock.prices" berarti mengambil dari Yahoo Finance
                        from = " 2016-01-01",
                        to = "2017-12-31")

tail(isat_validasi)
```

```{r}
colSums(is.na(isat_validasi))
```

```{r}
isat_sma2 <- isat_validasi

# SMA 5
isat_sma2$SMA5 <- SMA(Ad(isat_sma2),
                n = 5)

# SMA 30
isat_sma2$SMA20 <- SMA(Ad(isat_sma2),
                n = 20)

# SMA 50
isat_sma2$SMA60 <- SMA(Ad(isat_sma2),
                      n = 60)

# SMA 70
isat_sma2$SMA70 <- SMA(Ad(isat_sma2),
                n =70)
```


```{r}
isat_sma2 <- isat_sma2 %>%
  mutate(
    signal.SMA = case_when(
      adjusted < lag(SMA5, 1) & SMA20 > lag(SMA60, 1) ~ "Sell",
      adjusted > lag(SMA60, 1) & SMA20 < lag(SMA60, 1) ~ "Buy",
      TRUE ~ "Hold"
    ),
    previous_signal.SMA = lag(signal.SMA, 1),
    decision.SMA = case_when(
      signal.SMA == previous_signal.SMA ~ "Hold",
      TRUE ~ signal.SMA
    )
  )
```


```{r}
isat_sma2 %>% 
  filter(decision.SMA != "Hold" & ! is.na(SMA60))
```

```{r}
# Membuat objek baru 
isat_ema2 <- isat_validasi

# EMA 10
isat_ema2$EMA10 <- EMA(Ad(isat_ema2),
                n = 10)

# EMA 30
isat_ema2$EMA30 <- EMA(Ad(isat_ema2),
                n = 30)

# EMA 50
isat_ema2$EMA50 <- EMA(Ad(isat_ema2),
                n = 50)

# EMA 70
isat_ema2$EMA70 <- EMA(Ad(isat_ema2),
                n = 70)
```

```{r}
isat_ema2 <- isat_ema2 %>% 
  mutate(
    signal.EMA = case_when(
      adjusted < lag(EMA10, 1) & EMA30 > lag(EMA50, 1) ~ "Sell",
      adjusted > lag(EMA70, 1) & EMA30 < lag(EMA50, 1) ~ "Buy",
      TRUE ~ "Hold"# Otherwise sell
    ),
    previous_signal.EMA = lag(signal.EMA, 1), 
    decision.EMA = case_when( 
      signal.EMA == previous_signal.EMA ~ "Hold",
      TRUE ~ signal.EMA
    )
  )
```


```{r}
isat_ema2 %>% 
  filter(decision.EMA != "Hold" & ! is.na(EMA70))
```

```{r}
isat_macd2 <- isat_validasi

# EMA 10
isat_macd2$EMA10 <- EMA(Ad(isat_ema2),
                n = 10)

# EMA 18
isat_macd2$EMA18 <- EMA(Ad(isat_ema2),
                n = 18)

# EMA 48
isat_macd2$EMA48 <- EMA(Ad(isat_ema2),
                n = 48)

# MACD
isat_macd2$MACD <- isat_macd2$EMA18 - isat_macd2$EMA48
```


```{r}
isat_macd2 <- isat_macd2 %>% 
  mutate(
    signal.MACD = case_when(
      adjusted < lag(isat_macd2$EMA10, 1) & MACD < 0 & lag(MACD, 1) < MACD ~ "Buy", 
      adjusted > lag(isat_macd2$EMA10, 1) & MACD > 0 & lag(MACD, 1) > MACD ~ "Sell", 
      TRUE ~ "Hold"
    ),
    previous_signal.MACD = lag(signal.MACD, 1), 
    decision.MACD = case_when( 
      signal.MACD == previous_signal.MACD ~ "Hold",
      TRUE ~ signal.MACD
    )
  )
```


```{r}
isat_macd2 %>% 
  filter(decision.MACD != "Hold" & ! is.na(EMA48))
```


```{r}
isat_rsi2 <- isat_validasi

# RSI 10
isat_rsi2$RSI10 <- RSI(Ad(isat_rsi2),
                     n =10)

# RSI 38
isat_rsi2$RSI38 <- RSI(Ad(isat_rsi2), 
                      n=38)

# RSI 45
isat_rsi2$RSI45 <- RSI(Ad(isat_rsi2), 
                      n=45)

# RSI 70
isat_rsi2$RSI70 <- RSI(Ad(isat_rsi2), 
                      n=70)
```


```{r}
isat_rsi2 <- isat_rsi2 %>% 
  mutate(
    signal.RSI = case_when(
      adjusted < lag(adjusted,1) & RSI10 > RSI38 & RSI10 < RSI70 ~ "Buy",
      adjusted > lag(adjusted,1) & RSI10 < RSI38 & RSI10 > RSI45 ~ "Sell",
      TRUE ~ "Hold"
    ),
    previous_signal.RSI = lag(signal.RSI, 1),
    decision.RSI = case_when( 
      signal.RSI == previous_signal.RSI ~ "Hold",
      TRUE ~ signal.RSI
    )
  )
```


```{r}
isat_rsi2 %>% 
  filter(decision.RSI != "Hold" & ! is.na(RSI70))
```


```{r}
isat_analisa <- cbind(isat_validasi,isat_sma2$SMA5, isat_sma2$SMA20, isat_sma2$SMA60, isat_sma2$SMA70, isat_ema2$EMA10, isat_ema2$EMA30, isat_ema2$EMA50, isat_ema2$EMA70, isat_macd2$EMA10, isat_macd2$EMA18, isat_macd2$EMA48, isat_macd2$MACD, isat_rsi2$RSI10, isat_rsi2$RSI38, isat_rsi2$RSI45, isat_rsi2$RSI70, isat_sma2$decision.SMA, isat_ema2$decision.EMA, isat_macd2$decision.MACD, isat_rsi2$decision.RSI)

# Mengubah nama kolom
colnames(isat_analisa) <- c("symbol", "date", "open", "high", "low", "close", "volume", "adjusted", "SMA5", "SMA20", "SMA60", "SMA70", "EMA5", "EMA10", "EMA30", "EMA50", "EMA70", "EMA18", "EMA48", "MACD", "RSI10", "RSI38", "RSI45", "RSI70", "decision.SMA", "decision.EMA", "decision.MACD", "decision.RSI")

head(isat_analisa)
```


```{r}
isat_analisa <- isat_analisa %>% 
  mutate(
    final_decision = case_when(
      decision.SMA == "Buy" &  decision.EMA == "Buy" & decision.MACD == "Buy" & decision.RSI == "Buy" ~ "Buy",
      decision.SMA == "Sell" &  decision.EMA == "Buy" & decision.MACD == "Buy" & decision.RSI == "Buy" ~ "Buy",
      decision.SMA == "Buy" &  decision.EMA == "Sell" & decision.MACD == "Buy" & decision.RSI == "Buy" ~ "Buy",
      decision.SMA == "Buy" &  decision.EMA == "Buy" & decision.MACD == "Sell" & decision.RSI == "Buy" ~ "Buy",
      decision.SMA == "Buy" &  decision.EMA == "Buy" & decision.MACD == "Buy" & decision.RSI == "Sell" ~ "Buy",
      decision.SMA == "Sell" &  decision.EMA == "Sell" & decision.MACD == "Sell" & decision.RSI == "Sell" ~ "Sell",
      decision.SMA == "Buy" &  decision.EMA == "Sell" & decision.MACD == "Sell" & decision.RSI == "Sell" ~ "Sell",
      decision.SMA == "Sell" &  decision.EMA == "Buy" & decision.MACD == "Sell" & decision.RSI == "Sell" ~ "Sell",
      decision.SMA == "Sell" &  decision.EMA == "Sell" & decision.MACD == "Buy" & decision.RSI == "Sell" ~ "Sell",
      decision.SMA == "Sell" &  decision.EMA == "Sell" & decision.MACD == "Sell" & decision.RSI == "Buy" ~ "Sell",
      TRUE ~ "Hold"
    )
  )

isat_analisa %>% 
  filter(final_decision != "Hold")
```


```{r}
isat_analisa2 <- isat_analisa %>% 
  mutate(
    final_decision = case_when(
      decision.SMA == "Buy" &  decision.EMA == "Buy" & decision.MACD == "Buy" & decision.MACD == "Buy" | decision.EMA == "Buy" | decision.RSI == "Buy" ~ "Buy",
      decision.SMA == "Sell" &  decision.EMA == "Buy" & decision.MACD == "Buy" & decision.MACD == "Buy" | decision.EMA == "Buy" | decision.RSI == "Buy" ~ "Buy",
      decision.SMA == "Buy" &  decision.EMA == "Sell" & decision.MACD == "Buy" & decision.MACD == "Buy" | decision.EMA == "Buy" | decision.RSI == "Buy" ~ "Buy",
      decision.SMA == "Buy" &  decision.EMA == "Buy" & decision.MACD == "Sell" & decision.MACD == "Buy" | decision.EMA == "Buy" | decision.RSI == "Buy" ~ "Buy",
      decision.SMA == "Buy" &  decision.EMA == "Buy" & decision.MACD == "Buy" & decision.MACD == "Sell" | decision.EMA == "Buy" | decision.RSI == "Buy" ~ "Buy",
      decision.SMA == "Sell" &  decision.EMA == "Sell" & decision.MACD == "Sell" & decision.MACD == "Sell" | decision.EMA == "Sell" | decision.RSI == "Sell" ~ "Sell",
      decision.SMA == "Buy" &  decision.EMA == "Sell" & decision.MACD == "Sell" & decision.MACD == "Sell" | decision.EMA == "Sell" | decision.RSI == "Sell" ~ "Sell",
      decision.SMA == "Sell" &  decision.EMA == "Buy" & decision.MACD == "Sell" & decision.MACD == "Sell" | decision.EMA == "Sell" | decision.RSI == "Sell" ~ "Sell",
      decision.SMA == "Sell" &  decision.EMA == "Sell" & decision.MACD == "Buy" & decision.MACD == "Sell" | decision.EMA == "Sell" | decision.RSI == "Sell" ~ "Sell",
      decision.SMA == "Sell" &  decision.EMA == "Sell" & decision.MACD == "Sell" & decision.MACD == "Buy" | decision.EMA == "Sell" | decision.RSI == "Sell" ~ "Sell",
      TRUE ~ "Hold"
    )
  )
```


```{r}
isat_analisa2$final_decision[isat_analisa2$date == "2016-12-01"] <- "Hold"

isat_analisa2 %>%
  select(c("date", "open", "close", "final_decision")) %>% 
  filter(final_decision != "Hold")
```

```{r}
isat_x <- isat_analisa2[71:500,]
```


```{r}
isat_dt <- readRDS("isat_dt.RDS")
isat_rf <- readRDS("isat_forest.RDS")
```

```{r}
dt_pred <- predict(isat_dt, isat_x, type = "response")
head(dt_pred)
```

```{r}
eval_dt_validasi <- confusionMatrix(data = dt_pred,
                reference = as.factor(isat_x$final_decision))

table(isat_x$final_decision)
eval_dt_validasi
```

```{r}
isat_x$pred_dt <- dt_pred

isat_x
```

```{r}
isat_dt_backtest <- isat_x %>% 
  filter(pred_dt != "Hold") %>% 
  select(c("date", "open", "close", "final_decision", "pred_dt")) %>% 
  mutate(
    stock_buy = case_when(
      pred_dt == "Buy" ~ "1",
      TRUE ~ "0"
    )
  )

isat_dt_backtest <- isat_dt_backtest %>% 
  group_by(grp = cumsum(stock_buy==0)) %>%
  mutate(total_stock = ifelse(stock_buy==1, lag(cumsum(stock_buy==1))+1,0)) %>% 
  ungroup() %>% 
  select(-grp) %>%
  as.data.frame()

isat_dt_backtest <- isat_dt_backtest %>% 
  mutate(
    stock_sell = ifelse(pred_dt == "Sell", lag(total_stock),0)
    )

isat_dt_backtest <- isat_dt_backtest %>% 
  mutate(
    price_stock_bought = ifelse(pred_dt == "Buy", open*100,0)
    )

isat_dt_backtest <- isat_dt_backtest %>% 
  group_by(grp = cumsum(stock_buy==0)) %>%
  mutate(commulative_stock_price = ifelse(stock_buy==1, cumsum(price_stock_bought),0)) %>% 
  ungroup() %>% 
  select(-grp) %>%
  as.data.frame()

isat_dt_backtest <- isat_dt_backtest %>% 
  mutate(
    avg_price = ifelse(pred_dt == "Sell", lag(commulative_stock_price)/stock_sell,0)
    )

isat_dt_backtest <- isat_dt_backtest %>% 
  mutate(
    profit = ifelse(pred_dt == "Sell", (close*100 - avg_price)*stock_sell ,0)
    )

isat_dt_backtest

isat_dt_backtest %>% 
  filter(profit != 0 & profit != "NaN") %>% 
  summarise(total_proft = sum(profit))
```


```{r}
rf_pred <- predict(isat_rf, isat_x, type = "raw")
head(rf_pred)
```

```{r}
eval_rf_validasi <- confusionMatrix(data = rf_pred,
                reference = as.factor(isat_x$final_decision))

table(isat_x$final_decision)
eval_rf_validasi
```



```{r}
isat_x$pred_rf <- rf_pred

isat_x
```

```{r}
isat_rf_backtest <- isat_x %>% 
  filter(pred_rf != "Hold") %>% 
  select(c("date", "open", "close", "final_decision", "pred_rf")) %>% 
  mutate(
    stock_buy = case_when(
      pred_rf == "Buy" ~ "1",
      TRUE ~ "0"
    )
  )

isat_rf_backtest <- isat_rf_backtest %>% 
  group_by(grp = cumsum(stock_buy==0)) %>%
  mutate(total_stock = ifelse(stock_buy==1, lag(cumsum(stock_buy==1))+1,0)) %>% 
  ungroup() %>% 
  select(-grp) %>%
  as.data.frame()

isat_rf_backtest <- isat_rf_backtest %>% 
  mutate(
    stock_sell = ifelse(pred_rf == "Sell", lag(total_stock),0)
    )

isat_rf_backtest <- isat_rf_backtest %>% 
  mutate(
    price_stock_bought = ifelse(pred_rf == "Buy", open*100,0)
    )

isat_rf_backtest <- isat_rf_backtest %>% 
  group_by(grp = cumsum(stock_buy==0)) %>%
  mutate(commulative_stock_price = ifelse(stock_buy==1, cumsum(price_stock_bought),0)) %>% 
  ungroup() %>% 
  select(-grp) %>%
  as.data.frame()

isat_rf_backtest <- isat_rf_backtest %>% 
  mutate(
    avg_price = ifelse(pred_rf == "Sell", lag(commulative_stock_price)/stock_sell,0)
    )

isat_rf_backtest <- isat_rf_backtest %>% 
  mutate(
    profit = ifelse(pred_rf == "Sell", (close*100 - avg_price)*stock_sell ,0)
    )

isat_rf_backtest

isat_rf_backtest %>% 
  filter(profit != 0 & profit != "NaN") %>% 
  summarise(total_proft = sum(profit))
```