---
title: "Untitled"
author: "Victor Nugraha"
date: "7/23/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(rsconnect)

#data cleanup
library(tidyverse)
library(lubridate)

#data visualizaion
library(ggplot2)
library(plotly)
library(glue)

#data collection
library(quantmod)
library(tidyquant)

#data processing
library(TTR)

#cross validation
library(rsample)
library(UBL)
library(imbalance)
library(caret)

#model
library(partykit)
library(stats)
library(e1071)
```



```{r}
sido_validasi <- tq_get(x = "SIDO.JK", #Nama saham 
                        get = "stock.prices", #"stock.prices" berarti mengambil dari Yahoo Finance
                        from = " 2016-01-01",
                        to = "2017-12-31")

tail(sido_validasi)
```

```{r}
sido_validasi <- sido_validasi %>% 
  drop_na()

colSums(is.na(sido_validasi))
```

```{r}
#Membuat object baru
sido_sma2 <- sido_validasi

# SMA 5
sido_sma2$SMA5 <- SMA(Ad(sido_sma2),
                n = 5)
  
# SMA 15
sido_sma2$SMA15 <- SMA(Ad(sido_sma2),
                n = 15)

# SMA 55
sido_sma2$SMA55 <- SMA(Ad(sido_sma2),
                      n = 55)

# SMA 80
sido_sma2$SMA80 <- SMA(Ad(sido_sma2),
                n =80)
```


```{r}
sido_sma2 <- sido_sma2 %>%
  mutate(
    signal.SMA = case_when(
      adjusted < lag(SMA5, 1) & SMA15 < lag(SMA55, 1) ~ "Buy",
      adjusted > lag(SMA80, 1) & SMA15 > lag(SMA55, 1) ~ "Sell",
      TRUE ~ "Hold"
    ),
    previous_signal.SMA = lag(signal.SMA, 1),
    decision.SMA = case_when(
      signal.SMA == previous_signal.SMA ~ "Hold",
      TRUE ~ signal.SMA
    )
  )
```


```{r}
sido_sma2 %>% 
  filter(decision.SMA != "Hold" & ! is.na(SMA80))
```

```{r}
sido_sma2$decision.SMA[sido_sma2$date == "2017-05-03"] <- "Hold"
sido_sma2$decision.SMA[sido_sma2$date == "2017-05-08"] <- "Hold"

sido_sma2 %>% 
  filter(decision.SMA != "Hold" & ! is.na(SMA80))
```

```{r}
sido_ema2 <- sido_validasi

# EMA 5
sido_ema2$EMA5 <- EMA(Ad(sido_ema2),
                n = 5)

# EMA 30
sido_ema2$EMA30 <- EMA(Ad(sido_ema2),
                n = 30)

# EMA 55
sido_ema2$EMA55 <- EMA(Ad(sido_ema2),
                n = 55)

# EMA 60
sido_ema2$EMA60 <- EMA(Ad(sido_ema2),
                n = 60)
```

```{r}
sido_ema2 <- sido_ema2 %>% 
  mutate(
    signal.EMA = case_when(
      adjusted < lag(EMA5, 1) & EMA30 < lag(EMA55, 1) ~ "Buy",
      adjusted > lag(EMA60, 1) & EMA30 > lag(EMA55, 1) ~ "Sell",
      TRUE ~ "Hold"# Otherwise sell
    ),
    previous_signal.EMA = lag(signal.EMA, 1), 
    decision.EMA = case_when( 
      signal.EMA == previous_signal.EMA ~ "Hold",
      TRUE ~ signal.EMA
    )
  )
```


```{r}
sido_ema2$decision.EMA[sido_ema2$date == "2017-05-10"] <- "Hold"

sido_ema2 %>% 
  filter(decision.EMA != "Hold" & ! is.na(EMA60))
```

```{r}
sido_macd2 <- sido_validasi

# EMA 10
sido_macd2$EMA10 <- EMA(Ad(sido_macd2),
                n = 10)

# EMA 15
sido_macd2$EMA15 <- EMA(Ad(sido_macd2),
                n = 15)

# EMA 20
sido_macd2$EMA20 <- EMA(Ad(sido_macd2),
                n = 20)

# MACD
sido_macd2$MACD <- sido_macd2$EMA15 - sido_macd2$EMA20
```


```{r}
sido_macd2 <- sido_macd2 %>% 
  mutate(
    signal.MACD = case_when(
      adjusted < lag(sido_macd2$EMA10, 1) & MACD < 0 & lag(MACD, 1) < MACD ~ "Buy", 
      adjusted > lag(sido_macd2$EMA10, 1) & MACD > 0 & lag(MACD, 1) > MACD ~ "Sell", 
      TRUE ~ "Hold"
    ),
    previous_signal.MACD = lag(signal.MACD, 1), 
    decision.MACD = case_when( 
      signal.MACD == previous_signal.MACD ~ "Hold",
      TRUE ~ signal.MACD
    )
  )
```


```{r}
sido_macd2$decision.MACD[sido_macd2$date == "2017-11-02"] <- "Hold"

sido_macd2 %>% 
  filter(decision.MACD != "Hold" & ! is.na(EMA20))
```


```{r}
# Membuat objek baru
sido_rsi2 <- sido_validasi

# RSI 10
sido_rsi2$RSI10 <- RSI(Ad(sido_rsi2),
                     n =10)

# RSI 14
sido_rsi2$RSI14 <- RSI(Ad(sido_rsi2), 
                      n=14)

# RSI 30
sido_rsi2$RSI30 <- RSI(Ad(sido_rsi2), 
                      n=30)

# RSI 65
sido_rsi2$RSI65 <- RSI(Ad(sido_rsi2), 
                      n=65)
```


```{r}
sido_rsi2 <- sido_rsi2 %>% 
  mutate(
    signal.RSI = case_when(
      close < lag(close,1) & RSI10 > RSI14 & RSI10 < RSI65 ~ "Sell",
      close > lag(close,1) & RSI10 < RSI14 & RSI10 > RSI30 ~ "Buy",
      TRUE ~ "Hold"
    ),
    previous_signal.RSI = lag(signal.RSI, 1),
    decision.RSI = case_when( 
      signal.RSI == previous_signal.RSI ~ "Hold",
      TRUE ~ signal.RSI
    )
  )
```


```{r}
sido_rsi2$decision.RSI[sido_rsi2$date == "2016-08-03"] <- "Hold"
sido_rsi2$decision.RSI[sido_rsi2$date == "2016-08-08"] <- "Hold"

sido_rsi2 %>% 
  filter(decision.RSI != "Hold" & ! is.na(RSI65))
```


```{r}
# Menggabungkan kedalam sebuah data frame baru
sido_analisa <- cbind(sido_validasi, sido_sma2$SMA5, sido_sma2$SMA15, sido_sma2$SMA55, sido_sma2$SMA80, sido_ema2$EMA5, sido_ema2$EMA30, sido_ema2$EMA55, sido_ema2$EMA60, sido_macd2$EMA10, sido_macd2$EMA15, sido_macd2$MACD, sido_rsi2$RSI10, sido_rsi2$RSI14, sido_rsi2$RSI30, sido_rsi2$RSI65, sido_sma2$decision.SMA, sido_ema2$decision.EMA, sido_macd2$decision.MACD, sido_rsi2$decision.RSI)

# Mengubah nama kolom
colnames(sido_analisa) <- c("symbol", "date", "open", "high", "low", "close", "volume", "adjusted", "SMA5", "SMA15", "SMA55", "SMA80", "EMA5", "EMA30", "EMA55", "EMA60", "EMA10", "EMA15", "MACD", "RSI10", "RSI14", "RSI40", "RSI65", "decision.SMA", "decision.EMA", "decision.MACD", "decision.RSI")

head(sido_analisa)
```


```{r}
sido_analisa <- sido_analisa %>% 
  mutate(
    final_decision = case_when(
      decision.SMA == "Buy" &  decision.EMA == "Buy" & decision.MACD == "Buy" & decision.RSI == "Buy" ~ "Buy",
      decision.SMA == "Sell" &  decision.EMA == "Buy" & decision.MACD == "Buy" & decision.RSI == "Buy" ~ "Buy",
      decision.SMA == "Buy" &  decision.EMA == "Sell" & decision.MACD == "Buy" & decision.RSI == "Buy" ~ "Buy",
      decision.SMA == "Buy" &  decision.EMA == "Buy" & decision.MACD == "Sell" & decision.RSI == "Buy" ~ "Buy",
      decision.SMA == "Buy" &  decision.EMA == "Buy" & decision.MACD == "Buy" & decision.RSI == "Sell" ~ "Buy",
      decision.SMA == "Sell" &  decision.EMA == "Sell" & decision.MACD == "Sell" & decision.RSI == "Sell" ~ "Sell",
      decision.SMA == "Buy" &  decision.EMA == "Sell" & decision.MACD == "Sell" & decision.RSI == "Sell" ~ "Sell",
      decision.SMA == "Sell" &  decision.EMA == "Buy" & decision.MACD == "Sell" & decision.RSI == "Sell" ~ "Sell",
      decision.SMA == "Sell" &  decision.EMA == "Sell" & decision.MACD == "Buy" & decision.RSI == "Sell" ~ "Sell",
      decision.SMA == "Sell" &  decision.EMA == "Sell" & decision.MACD == "Sell" & decision.RSI == "Buy" ~ "Sell",
      TRUE ~ "Hold"
    )
  )

sido_analisa %>% 
  filter(final_decision != "Hold")
```


```{r}
sido_analisa2 <- sido_analisa %>% 
  mutate(
    final_decision = case_when(
      decision.SMA == "Buy" &  decision.EMA == "Buy" & decision.MACD == "Buy" & decision.RSI == "Buy" | decision.MACD == "Buy" | decision.RSI == "Buy" ~ "Buy",
      decision.SMA == "Sell" &  decision.EMA == "Buy" & decision.MACD == "Buy" & decision.RSI == "Buy" | decision.MACD == "Buy" | decision.RSI == "Buy" ~ "Buy",
      decision.SMA == "Buy" &  decision.EMA == "Sell" & decision.MACD == "Buy" & decision.RSI == "Buy" | decision.MACD == "Buy" | decision.RSI == "Buy" ~ "Buy",
      decision.SMA == "Buy" &  decision.EMA == "Buy" & decision.MACD == "Sell" & decision.RSI == "Buy" | decision.MACD == "Buy" | decision.RSI == "Buy" ~ "Buy",
      decision.SMA == "Buy" &  decision.EMA == "Buy" & decision.MACD == "Buy" & decision.RSI == "Sell" | decision.MACD == "Buy" | decision.RSI == "Buy" ~ "Buy",
      decision.SMA == "Sell" &  decision.EMA == "Sell" & decision.MACD == "Sell" & decision.RSI == "Sell" | decision.MACD == "Sell" | decision.RSI == "Sell" ~ "Sell",
      decision.SMA == "Buy" &  decision.EMA == "Sell" & decision.MACD == "Sell" & decision.RSI == "Sell" | decision.MACD == "Sell" | decision.RSI == "Sell" ~ "Sell",
      decision.SMA == "Sell" &  decision.EMA == "Buy" & decision.MACD == "Sell" & decision.RSI == "Sell" | decision.MACD == "Sell" | decision.RSI == "Sell" ~ "Sell",
      decision.SMA == "Sell" &  decision.EMA == "Sell" & decision.MACD == "Buy" & decision.RSI == "Sell" | decision.MACD == "Sell" | decision.RSI == "Sell" ~ "Sell",
      decision.SMA == "Sell" &  decision.EMA == "Sell" & decision.MACD == "Sell" & decision.RSI == "Buy" | decision.MACD == "Sell" | decision.RSI == "Sell" ~ "Sell",
      TRUE ~ "Hold"
    )
  )
```


```{r}
sido_analisa2$final_decision[sido_analisa2$date == "2016-02-09"] <- "Hold"
sido_analisa2$final_decision[sido_analisa2$date == "2016-11-04"] <- "Hold"
sido_analisa2$final_decision[sido_analisa2$date == "2017-01-10"] <- "Buy"
sido_analisa2$final_decision[sido_analisa2$date == "2016-02-09"] <- "Hold"

sido_analisa2 %>%
  select(c("date", "open", "close", "final_decision")) %>% 
  filter(final_decision != "Hold")
```

```{r}
sido_x <- sido_analisa2[81:492,]
```


```{r}
sido_dt <- readRDS("sido_dt.RDS")
sido_rf <- readRDS("sido_forest.RDS")
```

```{r}
dt_pred <- predict(sido_dt, sido_x_dt, type = "response")
head(dt_pred)
```

```{r}
eval_dt_validasi <- confusionMatrix(data = dt_pred,
                reference = as.factor(bbri_x$final_decision))

table(bbri_x$final_decision)
eval_dt_validasi
```

```{r}
bbri_x$pred_dt <- dt_pred

bbri_x
```

```{r}
bbri_dt_backtest <- bbri_x %>% 
  filter(pred_dt != "Hold") %>% 
  select(c("date", "open", "close", "final_decision", "pred_dt")) %>% 
  mutate(
    stock_buy = case_when(
      pred_dt == "Buy" ~ "1",
      TRUE ~ "0"
    )
  )

bbri_dt_backtest <- bbri_dt_backtest %>% 
  group_by(grp = cumsum(stock_buy==0)) %>%
  mutate(total_stock = ifelse(stock_buy==1, lag(cumsum(stock_buy==1))+1,0)) %>% 
  ungroup() %>% 
  select(-grp) %>%
  as.data.frame()

bbri_dt_backtest <- bbri_dt_backtest %>% 
  mutate(
    stock_sell = ifelse(pred_dt == "Sell", lag(total_stock),0)
    )

bbri_dt_backtest <- bbri_dt_backtest %>% 
  mutate(
    price_stock_bought = ifelse(pred_dt == "Buy", open*100,0)
    )

bbri_dt_backtest <- bbri_dt_backtest %>% 
  group_by(grp = cumsum(stock_buy==0)) %>%
  mutate(commulative_stock_price = ifelse(stock_buy==1, cumsum(price_stock_bought),0)) %>% 
  ungroup() %>% 
  select(-grp) %>%
  as.data.frame()

bbri_dt_backtest <- bbri_dt_backtest %>% 
  mutate(
    avg_price = ifelse(pred_dt == "Sell", lag(commulative_stock_price)/stock_sell,0)
    )

bbri_dt_backtest <- bbri_dt_backtest %>% 
  mutate(
    profit = ifelse(pred_dt == "Sell", (close*100 - avg_price)*stock_sell ,0)
    )

bbri_dt_backtest

bbri_dt_backtest %>% 
  filter(profit != 0 & profit != "NaN") %>% 
  summarise(total_proft = sum(profit))
```


```{r}
rf_pred <- predict(sido_rf, sido_x, type = "raw")
head(rf_pred)
```

```{r}
eval_rf_validasi <- confusionMatrix(data = rf_pred,
                reference = as.factor(sido_x$final_decision))

table(sido_x$final_decision)
eval_rf_validasi
```



```{r}
sido_x$pred_rf <- rf_pred

sido_x
```

```{r}
sido_rf_backtest <- sido_x %>% 
  filter(pred_rf != "Hold") %>% 
  select(c("date", "open", "close", "final_decision", "pred_rf")) %>% 
  mutate(
    stock_buy = case_when(
      pred_rf == "Buy" ~ "1",
      TRUE ~ "0"
    )
  )

sido_rf_backtest <- sido_rf_backtest %>% 
  group_by(grp = cumsum(stock_buy==0)) %>%
  mutate(total_stock = ifelse(stock_buy==1, lag(cumsum(stock_buy==1))+1,0)) %>% 
  ungroup() %>% 
  select(-grp) %>%
  as.data.frame()

sido_rf_backtest <- sido_rf_backtest %>% 
  mutate(
    stock_sell = ifelse(pred_rf == "Sell", lag(total_stock),0)
    )

sido_rf_backtest <- sido_rf_backtest %>% 
  mutate(
    price_stock_bought = ifelse(pred_rf == "Buy", open*100,0)
    )

sido_rf_backtest <- sido_rf_backtest %>% 
  group_by(grp = cumsum(stock_buy==0)) %>%
  mutate(commulative_stock_price = ifelse(stock_buy==1, cumsum(price_stock_bought),0)) %>% 
  ungroup() %>% 
  select(-grp) %>%
  as.data.frame()

sido_rf_backtest <- sido_rf_backtest %>% 
  mutate(
    avg_price = ifelse(pred_rf == "Sell", lag(commulative_stock_price)/stock_sell,0)
    )

sido_rf_backtest <- sido_rf_backtest %>% 
  mutate(
    profit = ifelse(pred_rf == "Sell", (close*100 - avg_price)*stock_sell ,0)
    )

sido_rf_backtest

sido_rf_backtest %>% 
  filter(profit != 0 & profit != "NaN") %>% 
  summarise(total_proft = sum(profit))
```